import { EmojiKey } from '../model/Emojis'

export const DUAL_EMOJIS_QUOTES: { [key in EmojiKey]: Array<string> } = {
	SEBASTIAN: [
		"Colo'shan synchronisée",
		"La Colo'shan esta synchronisada ma claro la mañana",
	],
	Duh: ["La Colo'shan est parfaitement demeurée", '**DUH**'],
	iyaya: [
		"Prenez garde à la montée d'énergie du Thero'shan",
		"Énergie du Thero'shan en hausse, merci de faire intervenir le Shan'do",
	],
	ui: [
		'w',
		"L'Instistut National de Recherche Dédiée à l'Étude de la Colo'shan (INRDEC) détecte une montée drastique de la baisabilité du Shan'do",
	],
	Proudbob: ["C'est mieux."],
	NANI: ['NANI ?!', 'NANI KELUYO OTTO-SAN KONICHIWA SUSHII DRAGON BALL ?!'],
	AngryRene: ["C'est hoNteux"],
	Perceval: ["C'est pas faux"],
	tuttut: ['TUT TUT'],
	CuteAnduin: ["VARIAN C L PER D'ANDUIN"],
	GABYhein: [],
	GABYseum: [],
	THOMASstyle: [],
	Deeplysad: [],
	boude: [],
	TomLaugh: [],
	ElRisitas: [],
	DeterAnduin: [],
	GeraltMh: [],
	GeraltLunettes: [],
	Sexbob: [],
	sadbob: [],
	AH: [],
	USBOY: [],
	wafreverse: [],
	PARDON: [],
	mh: [],
	what: [],
	Prune: [],
	CreverDansMonCoeur: [],
	Gneuhgneuhgneuh: [],
	cNon: [],
	TAGUEULE: [],
	hein: [],
	waf: [],
	fabuleux: [],
	robespieeeeeeerre: [],
	ANCULAR: [],
	bezmoi: [],
	THEFUCK: [],
	IMPACT: [],
	gabi: [],
	prophecy: [],
	sacbanane: [],
	poticha: [],
	ela: [],
	racoon: [],
	diggy: [],
	axa: [],
}
