import { EmojiKey } from '../model/Emojis'

export const DUAL_EMOJIS_QUOTES: { [key in EmojiKey]: Array<string> } = {
	SEBASTIAN: [
		'Muchos nachos',
		"La Colo'shan esta synchronisada ma claro la mañana",
		"Donde esta la playa de la colo'shana",
		'SEBASTIAN CASTELLANOS',
		'Sebastian ! Castellanos ! Inspecteur de ton coeur',
	],
	Duh: ["La Colo'shan est parfaitement demeurée", '**DUH**', 'g pa de cervo'],
	iyaya: [
		"Prenez garde à la montée d'énergie du Thero'shan",
		"Énergie du Thero'shan en hausse, merci de faire intervenir le Shan'do",
		"SHAN'DO G BOKOU DÉNERJI",
	],
	ui: [
		'w',
		"L'Instistut National de Recherche Dédiée à l'Étude de la Colo'shan (INRDEC) détecte une montée drastique de la baisabilité du Shan'do",
	],
	Proudbob: [
		"C'est mieux.",
		'Ta gueule Billy.',
		"J'm'en bas les couilles Billy.",
		"T'entends cette sonnerie Billy ? Elle indique qu'il est l'heure de te faire soulever.",
	],
	NANI: ['NANI ?!', 'NANI KELUYO OTTO-SAN KONICHIWA SUSHII DRAGON BALL ?!'],
	AngryRene: ["C'est hoNteux", "Mais on s'en BAT LES COUILLES"],
	Perceval: ["C'est pas faux", 'Je connais pas ce mot-là'],
	tuttut: ['TUT TUT'],
	GABYhein: [],
	GABYseum: [],
	THOMASstyle: [],
	Deeplysad: [],
	boude: [],
	TomLaugh: ['t kon', "z'êtes cons"],
	ElRisitas: ['Laugh in tacos', 'ISSOU'],
	CuteAnduin: ["VARIAN C LE PER D'ANDUIN"],
	DeterAnduin: ["VARIAN C LE PER D'ANDUIN"],
	GeraltMh: ['Mhhhhhhhhhhhhhhhhhhhhh', 'Mh', 'Fuck'],
	GeraltLunettes: [],
	Sexbob: ['Le PLAISIIIIIIIIR'],
	sadbob: [],
	AH: ['AH'],
	USBOY: ['Où sont les french girls ?'],
	wafreverse: [],
	PARDON: [],
	mh: [],
	what: [],
	Prune: [],
	CreverDansMonCoeur: ["P'tit chat", 'Miaou', "C'est pas l'emote le problème"],
	Gneuhgneuhgneuh: [],
	cNon: [],
	TAGUEULE: [],
	hein: [],
	waf: [],
	fabuleux: [],
	robespieeeeeeerre: [
		"Vous serez raccourcis d'une tête au niveau du cou.",
		'**LA RÉPUBLIQUE DANS TA BOUCHE**',
		'**TU LA SENS MA GROSSE RÉPUBLIQUE ??**',
	],
	ANCULAR: [],
	bezmoi: [],
	THEFUCK: [],
	IMPACT: [],
	gabi: ['keske'],
	prophecy: [],
	sacbanane: [],
	poticha: [],
	ela: [],
	racoon: [],
	diggy: ["J'vais tous vous fumer."],
	axa: [],
}
