import { EmojiKey } from '../../model/Emojis'

export const DUAL_EMOJIS_QUOTES: {
	[key in EmojiKey]: Array<string>
} = {
	SEBASTIAN: [
		'Muchos nachos',
		"La Colo'shan esta synchronisada ma claro la mañana",
		"Donde esta la playa de la colo'shana",
		'SEBASTIAN CASTELLANOS',
		'Sebastian ! Castellanos ! Inspecteur de ton coeur',
	],
	Duh: ["La Colo'shan est parfaitement demeurée", '**DUH**', 'g pa de cervo'],
	iyaya: [
		"Prenez garde à la montée d'énergie du Thero'shan",
		"Énergie du Thero'shan en hausse, merci de faire intervenir le Shan'do",
		"SHAN'DO G BOKOU DÉNERJI",
	],
	ui: [
		'w',
		"L'Instistut National de Recherche Dédiée à l'Étude de la Colo'shan (INRDEC) détecte une montée drastique de la baisabilité du Shan'do",
	],
	Proudbob: [
		"C'est mieux.",
		'Ta gueule Billy.',
		"J'm'en bats les couilles Billy.",
		"T'entends cette sonnerie Billy ? Elle indique qu'il est l'heure de te faire soulever.",
	],
	NANI: ['NANI ?!', 'NANI KELUYO OTTO-SAN KONICHIWA SUSHII DRAGON BALL ?!'],
	AngryRene: ["C'est hoNteux", "Mais on s'en BAT LES COUILLES"],
	Perceval: ["C'est pas faux", 'Je connais pas ce mot-là'],
	tuttut: ['TUT TUT', 'Tut tut fils de pute'],
	GABYhein: ["Mais j'vais te faire le fion"],
	GABYseum: ['nik toi'],
	THOMASstyle: ["I'm a bitch, I'm a boss"],
	Deeplysad: [],
	boude: [],
	Tomlaugh: ['t kon', "z'êtes cons"],
	ElRisitas: ['Laugh in tacos', 'ISSOU', "Un peu d'issou, pas trop"],
	CuteAnduin: ["VARIAN C LE PER D'ANDUIN"],
	DeterAnduin: ["VARIAN C LE PER D'ANDUIN"],
	GeraltMh: ['Mhhhhhhhhhhhhhhhhhhhhh', 'Mh', 'Fuck'],
	GeraltLunettes: ['Laissez les ingénieurs faire', 'Engineers in da place'],
	Sexbob: ['Le PLAISIIIIIIIIR', '**HAAAAAAAAAAAAAAN**'],
	sadbob: ["Y'a pu de respect Billy", "J'ai mal au cul Billy"],
	AH: ['AH', 'Donc les femmes ne savent pas construire de cabane ?'],
	USBOY: ['Où sont les french girls ?'],
	wafreverse: ['waf'],
	PARDON: ['NANI ?', "QU'EST CE À DIRE QUE CECI ?"],
	mh: ['mhhhhhhh', '**MMMHHHHHHHHHH**'],
	what: ['wat'],
	Prune: ['Prune.exe a cessé de fonct'],
	CreverDansMonCoeur: ["P'tit chat", 'Miaou', "C'est pas l'emote le problème"],
	Gneuhgneuhgneuh: ["vArIaN c lE pÈrE d'aNdUiN"],
	cNon: ["C'est non.", "Eeeeeeeeeeeeeeeeeeeeeeeeeeet c'est non."],
	TAGUEULE: ["**OUAIS MAIS C'EST PAS TOI QUI DÉCIDE**", '**TA GUEULE**'],
	hein: ['bark ?', 'waf ?', 'woof woof ?', 'donde estan las croquettas ?'],
	waf: ['waf'],
	fabuleux: ['Feels goooooood'],
	robespieeeeeeerre: [
		"Vous serez raccourcis d'une tête au niveau du cou.",
		'**LA RÉPUBLIQUE DANS TA BOUCHE**',
		'**TU LA SENS MA GROSSE RÉPUBLIQUE ??**',
	],
	ANCULAR: ['ANCULAR'],
	bezmoi: [
		'Pratique le coït avec ma personne, je te prie',
		"Vous savez quelle heure il est ? L'heure de me baiser.",
	],
	THEFUCK: ['PITIÉ MONSIEUR', 'Pitié monsieur'],
	IMPACT: ['**TIR A IMPACT**', 'IMPACT DANS TA BOUCHE'],
	gabi: ['keske'],
	prophecy: [],
	sacbanane: ['Et pourquoi pas le Maître de la banane ?'],
	poticha: ['Miaou ?!'],
	ela: ['Qui a emmerdé ma femme ?'],
	racoon: ['Raccoonax 2000 in da place'],
	diggy: ["J'vais tous vous fumer.", "Oh c'est l'heure de te péter le cul"],
	axa: ['Éwé', 'Bawi'],
	rocket: ['Rocketto', 'Meooooooooow', 'Miaou bordel de merde'],
	deadInside: [
		'*Listening to* Suzuya - Dis-moi que tu me détestes',
		'*Listening to* Nekfeu - Avant tu riais',
		'*Listening to* 12 Stones - Hello Suicide',
	],
	copbear: ['**POLICE DES POMPONS**', "C'est la police tavu"],
	comfyRocket: ['Rocketto dodo', 'Just Rocketting'],
	helicochien: ['tuh-tuh-tuh-tuh-tuh-tuh-tuh-tuh', '**LE CHIEN**'],
	kindasusdance: [],
	mizu: ['Gratouilles. Now.'],
	point_gun_reverse: [],
	point_gun: [],
	raccoondance: [],
	winniejuge: ['Mais ... Quoi ?'],
	lyzuneMeh: ["Je... D'accord."],
	lyzuneSweat: [],
	lyzuneHappy: [],
	pecheWhat: ['De koi ?', 'kwa ?', "Zoval, c'est le joallier ?"],
	pecheWow: [
		'Oh des saucisses !',
		'Ce serait encore mieux avec des saucisses !',
		'Oh un nain disco',
	],
	pecheAngry: [
		'Greuh.',
		"C'est toi qui a mangé toutes les saucisses ?",
		'Rends les saucisses',
	],
}
